### ISSUE TITLE
New command request: Server Stats

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot-v1#12]
To add a feature to the bot which keeps count of the number of members in the server.

_Originally posted by @aritra-sarkar99 in https://github.com/DSCKGEC/community-discord-bot/issues/9#issuecomment-702750018_

**Comment by Andreybest** [comment]
Hello, I can make such feature. Can you assign this one to me?

**Comment by singhayushh** [comment]
@Andreybest 
Thanks for connecting
We'd like to inform you that the Original Poster, @aritra-sarkar99 had raised this issue and wanted to cover it himself.
This was yesterday in comment [#9 here](https://github.com/DSCKGEC/community-discord-bot/issues/9#issuecomment-702750018)
Please have a talk with him if you'd want to take the task from him.

Btw, if you have any other ideas in mind for the bot, do bring it forward by raising a new issue - we'll be glad to assign it to you!

**Comment by aritra-sarkar99** [comment]
@singhayushh I have finished making the server stats. I will send a Pull Request soon.
