### ISSUE TITLE
Functionality needed: Changing nicknames

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot-v1#13]
Hello 👋🏼,
We currently need some commands for our bot and contributions are welcome!
> We would be listing each required command in separate issues for convenience.

#### About this issue
Currently, after #10, the bot is triggered to DM every new user asking the user's name and college only to assign him/her a specified role if he is from our college. Apart from this functionality, we would also want the bot to change the user's nickname in our server to the name he answers to the bot when DMed (independent of his college).

Let us know in the comments if you are interested in contributing!

**Comment by AyushRajSharma** [comment]
can i do it??
please assign me, i wanna do it

**Comment by singhayushh** [comment]
Sure @AyushRajSharma !
